### ISSUE TITLE
[feature]: Updates from the latest VS Code code-base?

### ISSUE THREAD

**Issue by dankeboy36** [connor4312/evt#1]
Thank you for the great lib!

Are there any plans to update it from the latest VS Code sources: [src/vs/base/common/event.ts](https://github.com/microsoft/vscode/blob/6c2faf1c5db3a438360b44a9f7b83bafac8efa0b/src/vs/base/common/event.ts) and [src/vs/base/common/lifecycle.ts](https://github.com/microsoft/vscode/blob/6c2faf1c5db3a438360b44a9f7b83bafac8efa0b/src/vs/base/common/lifecycle.ts)?

**Comment by connor4312** [comment]
I don't want to copy it verbatim. Since https://github.com/microsoft/vscode/pull/185889 the event system in VS Code is actually based on this library, but it also adds several esoteric cases (e.g. sequence coordination between multiple event emitters) that consumers of this library wouldn't care about and would just make the API more bulky.

**Comment by dankeboy36** [comment]
> I don't want to copy it verbatim.

Thanks for considering it.

> but it also adds several esoteric cases

It also adds excellent utilities (buffer, once, fromNodeEventEmitter, any, etc.) that could be (re)used in the extension code, but I understand you want to keep this lib small.

Keep up the great work 💪
